# 端口号
server:
  port: 8888

# 数据库连接配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gmall

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  # 开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true


